- name: install required packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - redis-server

- replace: dest=/etc/redis/redis.conf regexp='127.0.0.1' replace='0.0.0.0' 
  notify: restart_redis

